export default {
  login: '1app0',
  id: 56257295,
  node_id: 'MDQ6VXNlcjU2MjU3Mjk1',
  avatar_url: 'https://avatars.githubusercontent.com/u/56257295?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/1app0',
  html_url: 'https://github.com/1app0',
  followers_url: 'https://api.github.com/users/1app0/followers',
  following_url: 'https://api.github.com/users/1app0/following{/other_user}',
  gists_url: 'https://api.github.com/users/1app0/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/1app0/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/1app0/subscriptions',
  organizations_url: 'https://api.github.com/users/1app0/orgs',
  repos_url: 'https://api.github.com/users/1app0/repos',
  events_url: 'https://api.github.com/users/1app0/events{/privacy}',
  received_events_url: 'https://api.github.com/users/1app0/received_events',
  type: 'User',
  site_admin: false,
  name: 'Alex Vasilianov',
  company: null,
  blog: '',
  location: 'Horsens, Denmark',
  email: 'vasilianov1@gmail.com',
  hireable: true,
  bio: 'Software Engineer student at VIA University College',
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: '2019-10-07T11:22:58Z',
  updated_at: '2021-03-17T08:01:05Z',
}
